name: dggs-benchmarking
channels:
  - conda-forge
dependencies:
  - dask-jobqueue
  - dask-labextension
  - dask>=2.3
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - python
  - scipy
  - xarray>=0.12.3
  - zarr
