name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:

    name: Test benchmarking package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Install package
      run: |
        python -m pip install -e ".[test]"
      shell: bash -el {0}
    - name: Test with pytest
      run: |
        python -m pytest --cov=benchmark --cov-report html --cov-report xml --cov-report term-missing -v
      shell: bash -el {0}
    - name: Coverage report
      run: |
        python3 -m coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
        python3 -m coverage json
        export TOTAL=$(python3 -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
        echo "total=$TOTAL" >> $GITHUB_ENV
      shell: bash -el {0}
    - name: Upload HTML report.
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: htmlcov
